### PR TITLE
Add the initial code for the temperature converter

### PR DESCRIPTION
**Pull request by Jacalz**
It is a bit ugly with a hack to workaround `entry.SetText()` triggering the `entry.OnChanged()` function along with ugly string, int and float conversion. Anyhow, it works and looks good rendered :)

### CODE REVIEW

**Comment by Jacalz** [comment]
FYI, this is my first open source code contribution ever :champagne:

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Great contribution, thanks.

To avoid the human flag would it work if you set the text directly (inputF.Text = ...) followed by a call to Refresh().
I think that the ContainsAny check is not quite correct - it will pass if any numbers are found, but it should check to see if they are *only* numbers (including decimal point) - maybe this post will help? https://stackoverflow.com/questions/45686163/how-to-write-isnumeric-function-in-golang/45686455

Lastly the two labels could be created inline to avoid a few more lines of code :)

**Comment by andydotxyz** [comment]
Congratulations on your first ever contribution, this was really close. A few tweaks and we could land it I'm sure :)

**Comment by Jacalz** [comment]
I have updated the code according to the code review. I haven't had the time to test it yet, but I will do that later today.

**Comment by andydotxyz** [comment]
Thanks for updating - but please don’t push code you haven’t tested

**Comment by Jacalz** [comment]
Yeah you are right. It was stupid, I really don't know what I thought at the time :slightly_frowning_face:

**Comment by andydotxyz** [comment]
Thanks for this. I don't think we can merge it until the text updating is fixed.
To get it in sooner maybe a similar workaround to before is required?

**Comment by Jacalz** [comment]
Yeah I think you are right. I can add back the workaround and then submit a new PR when the issue is fixed upstream.

**Comment by Jacalz** [comment]
The workaround has been applied again until the bug gets fixed upstream :+1:

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Thanks for doing this. 
Unfortunately the new lines are not embedded correctly (gofmt will fix this) and the import order is wrong.

**Comment by Jacalz** [comment]
I think this should suffice now :)

**Review by andydotxyz — APPROVED** [review]

**Comment by Jacalz** [comment]
Thanks for merging. All that is missing now is an image in the README.md file :)

**Comment by andydotxyz** [comment]
You're welcome to PR that as well ;)

**Comment by Jacalz** [comment]
There is a reason that I never included a picture, it would not be consistent with the other picture in the readme 😉

**Comment by andydotxyz** [comment]
done

**Pull request merged**
